"""empty message

Revision ID: 7210284bf3ca
Revises:
Create Date: 2019-07-06 01:25:25.736809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7210284bf3ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('sku', sa.Unicode(), nullable=False),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=u'true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=u'false'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
